### PR TITLE
New syntax

### PR DESCRIPTION
**Pull request by crackcomm**
New Reason syntax in `create-react-app` template.

### CODE REVIEW

**Comment by anmonteiro** [comment]
@crackcomm I think you need to add a `"refmt": 3` entry to this file: https://github.com/reasonml-community/reason-scripts/blob/master/template/bsconfig.json

**Comment by crackcomm** [comment]
Thanks, I squashed it.

**Comment by anmonteiro** [comment]
There seems to be yet another failure but I'm not familiar with it.

`Cannot find module 'babel-loader'`

**Comment by rrdelaney** [comment]
Hey @crackcomm 😄 Thanks so much for submitting this PR! It's really nice to have everyone on the new syntax already!

I just published these changes and they should be available as `v0.7.0` on npm

**Pull request merged**
