### PR TITLE
added bs-fetch to bs-dependencies

### PR DESCRIPTION
**Pull request by shrynx**
added bs-fetch as a dependency as fetch is already added as a polyfill.
https://github.com/reasonml-community/reason-scripts/blob/master/config/polyfills.js#L20

### CODE REVIEW

**Comment by rrdelaney** [comment]
Omg yes :heart: Thanks!!!

**Comment by shrynx** [comment]
sorry it is failing, i was doing it half asleep, will fit it soon.

**Comment by rrdelaney** [comment]
I just fixed up some merge conflicts from the `v0.9` branch :smile:

**Comment by shrynx** [comment]
Oh nice thanks a lot 😄

**Comment by rrdelaney** [comment]
Also, don't worry about the tests, they've been broken for a while.

**Pull request merged**
